#!/usr/bin/env python3
"""Render the agent-safehouse env sidecar at ~/.config/agent-safehouse/env.sh.

Writes a POSIX-shell sidecar exporting SAFEHOUSE_APPEND_PROFILE and
defining two wrapper functions (`safe`, `safe-claude`) verbatim from
the eugene1g/agent-safehouse README. The user adds one line to their
shell rc to source both this sidecar and the clearance one — see
render_clearance_env.py's header for the snippet.

Also writes an empty `~/.config/agent-safehouse/local-overrides.sb`
stub if missing, so the wrapper's `--append-profile=...` flag points
at a real (if empty) file from day one. Pass --no-overrides-stub to
skip this side-effect.

Smart-merge: any of SAFEHOUSE_APPEND_PROFILE / safe / safe-claude
already defined (uncommented) in the user's shell rc is commented out
in the sidecar with a one-line note pointing at the rc location.

Atomic write: tempfile in target dir + fsync + os.replace.

Exit codes:
  0  on success
  1  on I/O / permission errors

JSON output on stdout:
  {"target": "<path>", "wrote": true,
   "rcConflicts": [{"item": "<name>", "file": "<path>", "line": <int>}, ...],
   "overridesStub": "<path>|null"}
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tempfile
from pathlib import Path
from typing import TypedDict

VAR_APPEND_PROFILE = "SAFEHOUSE_APPEND_PROFILE"
FN_SAFE = "safe"
FN_SAFE_CLAUDE = "safe-claude"

RC_CANDIDATES = (".zshrc", ".bash_profile", ".bashrc", ".profile")

# Anchored patterns. A bare substring match for the var name flags any line that
# mentions it (e.g. `echo "set $VAR"`, an unset alias). Function patterns match
# `name()` at the start of a stripped line, with optional whitespace.
_EXPORT_RE = re.compile(rf"^\s*export\s+{re.escape(VAR_APPEND_PROFILE)}(?=[=\s]|$)")
_FN_RE = {
    FN_SAFE: re.compile(r"^\s*safe\s*\(\s*\)"),
    FN_SAFE_CLAUDE: re.compile(r"^\s*safe-claude\s*\(\s*\)"),
}


class RcMatch(TypedDict):
    item: str
    file: str
    value: str | None
    line: int


def scan_rc(home: Path) -> dict[str, RcMatch]:
    """Return {item: RcMatch} for items defined (uncommented) in any rc file.

    Items scanned: SAFEHOUSE_APPEND_PROFILE export, safe() definition,
    safe-claude() definition. First match wins per item; rc candidates
    are scanned in canonical login order.

    For the SAFEHOUSE_APPEND_PROFILE export, the matched line's RHS is
    captured into `value` so the sidecar's commented note can show the
    actual path the rc points at, not the wizard's default.
    """
    found: dict[str, RcMatch] = {}
    items_to_find = {VAR_APPEND_PROFILE, FN_SAFE, FN_SAFE_CLAUDE}

    for rc_name in RC_CANDIDATES:
        rc_path = home / rc_name
        try:
            with rc_path.open("r", encoding="utf-8") as fh:
                for line_num, line in enumerate(fh, start=1):
                    stripped = line.strip()
                    if not stripped or stripped.startswith("#"):
                        continue
                    if VAR_APPEND_PROFILE not in found and _EXPORT_RE.match(stripped):
                        value = _extract_export_value(stripped, VAR_APPEND_PROFILE)
                        found[VAR_APPEND_PROFILE] = RcMatch(
                            item=VAR_APPEND_PROFILE, file=str(rc_path),
                            value=value, line=line_num,
                        )
                    for fn_name, pattern in _FN_RE.items():
                        if fn_name in found:
                            continue
                        if pattern.match(line):
                            found[fn_name] = RcMatch(
                                item=fn_name, file=str(rc_path),
                                value=None, line=line_num,
                            )
        except OSError:
            continue
        if set(found.keys()) >= items_to_find:
            break
    return found


def _extract_export_value(stripped_line: str, var: str) -> str | None:
    """Return the RHS of `export VAR=...`, stripped of optional surrounding quotes.

    Returns None if the line is `export VAR` alone (declaration without value),
    or if the value can't be cleanly extracted.
    """
    m = re.match(rf"^\s*export\s+{re.escape(var)}=(.*)$", stripped_line)
    if not m:
        return None
    raw = m.group(1).strip()
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in ('"', "'"):
        return raw[1:-1]
    return raw or None


def render_sidecar(rc_conflicts: dict[str, RcMatch], overrides_path: Path) -> str:
    """Build the sidecar body. Conflicting items are commented with a note."""
    lines: list[str] = [
        "# Generated by /groundcrew-setup:safehouse — safe to regenerate.",
        "# Source this from your shell rc:",
        "#   for f in ~/.config/clearance/env.sh ~/.config/agent-safehouse/env.sh; do",
        '#     [ -f "$f" ] && . "$f"',
        "#   done",
        "",
        f"# {VAR_APPEND_PROFILE} — path to your machine-local policy overrides.",
    ]
    if VAR_APPEND_PROFILE in rc_conflicts:
        m = rc_conflicts[VAR_APPEND_PROFILE]
        # Show the rc's actual value, not the wizard's default — the commented-out
        # line is for diagnostic clarity, not a fallback definition.
        rc_value = m.get("value") or "(see rc line for value)"
        lines.append(f"# Already exported in {m['file']}:{m['line']} — sidecar leaving this alone.")
        lines.append(f'# (rc value: "{rc_value}")')
    else:
        lines.append(f'export {VAR_APPEND_PROFILE}="{overrides_path}"')
    lines.append("")

    # safe() function.
    lines.append("# safe — wrapper that always applies your append-profile.")
    safe_body = [
        "safe() {",
        "  safehouse \\",
        f'    --append-profile="${VAR_APPEND_PROFILE}" \\',
        '    "$@"',
        "}",
    ]
    if FN_SAFE in rc_conflicts:
        m = rc_conflicts[FN_SAFE]
        lines.append(f"# Already defined in {m['file']}:{m['line']} — sidecar leaving this alone.")
        for body_line in safe_body:
            lines.append(f"# {body_line}" if body_line else "#")
    else:
        lines.extend(safe_body)
    lines.append("")

    # safe-claude() function.
    lines.append("# safe-claude — convenience wrapper for sandboxed claude code.")
    safe_claude_body = [
        "safe-claude() {",
        '  safe claude --dangerously-skip-permissions "$@"',
        "}",
    ]
    if FN_SAFE_CLAUDE in rc_conflicts:
        m = rc_conflicts[FN_SAFE_CLAUDE]
        lines.append(f"# Already defined in {m['file']}:{m['line']} — sidecar leaving this alone.")
        for body_line in safe_claude_body:
            lines.append(f"# {body_line}" if body_line else "#")
    else:
        lines.extend(safe_claude_body)
    lines.append("")
    return "\n".join(lines)


OVERRIDES_STUB = """\
;; ~/.config/agent-safehouse/local-overrides.sb
;;
;; Empty stub created by /groundcrew-setup:safehouse so the
;; SAFEHOUSE_APPEND_PROFILE flag resolves to a real file from day one.
;;
;; Add machine-local sandbox-exec rules below; see
;; https://agent-safehouse.dev/docs/ for the policy DSL.
;;
;; Example:
;;   (allow file-read*
;;     (home-literal "/.gitignore_global")
;;     (subpath "/Volumes/Shared/Engineering"))
"""


def write_atomic(target: Path, content: str, mode: int = 0o644) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path_str = tempfile.mkstemp(
        prefix="." + target.name + ".",
        dir=str(target.parent),
        text=False,
    )
    tmp_path = Path(tmp_path_str)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
        os.chmod(tmp_path, mode)
        os.replace(tmp_path, target)
    except OSError:
        try:
            tmp_path.unlink()
        except OSError:
            pass
        raise


def main(argv: list[str]) -> int:
    home = Path(os.environ.get("HOME") or os.path.expanduser("~"))
    default_target = home / ".config" / "agent-safehouse" / "env.sh"

    parser = argparse.ArgumentParser(
        description="Render the agent-safehouse env sidecar.",
    )
    parser.add_argument(
        "--target",
        default=str(default_target),
        help=f"Sidecar path (default: {default_target}).",
    )
    parser.add_argument(
        "--overrides-file",
        default=None,
        help=(
            "Path to write (or reference) the local-overrides.sb file. "
            "Defaults to <target_dir>/local-overrides.sb — derived from --target "
            "so a custom --target keeps the stub colocated with the sidecar."
        ),
    )
    parser.add_argument(
        "--no-overrides-stub",
        action="store_true",
        help="Skip creating the local-overrides.sb stub even if absent.",
    )
    args = parser.parse_args(argv)

    target = Path(args.target)
    # When --overrides-file is not specified, derive it from --target's parent so
    # a custom --target keeps the stub colocated with the sidecar instead of
    # landing at the fixed default. This avoids the split-paths failure mode
    # where the sidecar at /A references a stub at /B.
    overrides_path = (
        Path(args.overrides_file) if args.overrides_file is not None
        else target.parent / "local-overrides.sb"
    )
    rc_conflicts = scan_rc(home)
    content = render_sidecar(rc_conflicts, overrides_path)

    overrides_written: str | None = None
    try:
        write_atomic(target, content)
        if not args.no_overrides_stub and not overrides_path.exists():
            write_atomic(overrides_path, OVERRIDES_STUB)
            overrides_written = str(overrides_path)
    except OSError as exc:
        print(json.dumps({
            "target": str(target),
            "wrote": False,
            "error": f"{exc.__class__.__name__}: {exc}",
        }))
        return 1

    print(json.dumps({
        "target": str(target),
        "wrote": True,
        "rcConflicts": list(rc_conflicts.values()),
        "overridesStub": overrides_written,
    }))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
