#!/usr/bin/env python3
"""Render the clearance env sidecar at ~/.config/clearance/env.sh.

The sidecar exports two variables that `@clipboard-health/clearance`
reads at daemon start:
  CLEARANCE_ALLOW_HOSTS_FILES  colon-separated list of allowlist files
  CLEARANCE_PERSONAL_HOSTS     opt-in flag for appending the personal file

A user adds ONE line to their shell rc:
  for f in ~/.config/clearance/env.sh ~/.config/agent-safehouse/env.sh; do
    [ -f "$f" ] && . "$f"
  done

Smart-merge: if the user already has either export in a shell rc file
(e.g. ~/.zshrc:169 — the layout this PR's smoke test discovered on the
author's machine), the sidecar writes a commented-out copy of that
export with a one-line note pointing at the rc location, instead of
duplicating it. The dotfile manager (chezmoi/yadm/stow) keeps owning
the rc entry; the sidecar owns the rest.

Atomic write: tempfile in target dir + fsync + os.replace.

Exit codes:
  0  on success
  1  on I/O / permission errors

JSON output on stdout:
  {"target": "<path>", "wrote": true,
   "rcConflicts": [{"var": "<name>", "file": "<path>", "line": <int>}, ...]}
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path
from typing import TypedDict

VAR_ALLOW_HOSTS = "CLEARANCE_ALLOW_HOSTS_FILES"
VAR_PERSONAL = "CLEARANCE_PERSONAL_HOSTS"

# `$(...)` expands at source-time so the absolute path stays current
# even when the user upgrades groundcrew via `npm update -g`.
ALLOW_HOSTS_VALUE = (
    '"$(npm root -g)/@clipboard-health/groundcrew/clearance-allow-hosts'
    '${CLEARANCE_PERSONAL_HOSTS:+:$HOME/.config/clearance/personal-allow-hosts}"'
)

RC_CANDIDATES = (".zshrc", ".bash_profile", ".bashrc", ".profile")


class RcMatch(TypedDict):
    var: str
    file: str
    line: int


def scan_rc(home: Path, var_names: tuple[str, ...]) -> dict[str, RcMatch]:
    """Return {var: RcMatch} for vars exported (uncommented) in any rc candidate.

    First match wins; rc candidates are scanned in the canonical order used
    by login shells (zshrc first on macOS).
    """
    found: dict[str, RcMatch] = {}
    for rc_name in RC_CANDIDATES:
        rc_path = home / rc_name
        try:
            with rc_path.open("r", encoding="utf-8") as fh:
                for line_num, line in enumerate(fh, start=1):
                    stripped = line.strip()
                    if not stripped or stripped.startswith("#"):
                        continue
                    for var in var_names:
                        if var in found:
                            continue
                        if var in stripped:
                            found[var] = RcMatch(var=var, file=str(rc_path), line=line_num)
        except OSError:
            continue
        if set(found.keys()) >= set(var_names):
            break
    return found


def render_sidecar(rc_conflicts: dict[str, RcMatch]) -> str:
    """Build the sidecar body. Conflicting vars are commented with a note.

    Order matters: CLEARANCE_PERSONAL_HOSTS must be set before
    CLEARANCE_ALLOW_HOSTS_FILES, because the `${PERSONAL_HOSTS:+...}`
    expansion inside the ALLOW_HOSTS value happens at export time, not
    lazily. With the reverse order, the personal-file branch silently
    drops out and only the baseline file is in the allowlist.
    """
    lines: list[str] = [
        "# Generated by /groundcrew-setup:clearance — safe to regenerate.",
        "# Source this from your shell rc:",
        "#   for f in ~/.config/clearance/env.sh ~/.config/agent-safehouse/env.sh; do",
        '#     [ -f "$f" ] && . "$f"',
        "#   done",
        "",
        f"# {VAR_PERSONAL} — opt into the personal allowlist append.",
        f"# Exported FIRST so the ${{{VAR_PERSONAL}:+...}} branch below resolves.",
    ]
    if VAR_PERSONAL in rc_conflicts:
        m = rc_conflicts[VAR_PERSONAL]
        lines.append(f"# Already exported in {m['file']}:{m['line']} — sidecar leaving this alone.")
        lines.append(f"# export {VAR_PERSONAL}=1")
    else:
        lines.append(f"export {VAR_PERSONAL}=1")
    lines.append("")
    lines.append(f"# {VAR_ALLOW_HOSTS} — groundcrew's baseline allowlist, plus your")
    lines.append(f"# personal allowlist when {VAR_PERSONAL} is set.")
    if VAR_ALLOW_HOSTS in rc_conflicts:
        m = rc_conflicts[VAR_ALLOW_HOSTS]
        lines.append(f"# Already exported in {m['file']}:{m['line']} — sidecar leaving this alone.")
        lines.append(f"# export {VAR_ALLOW_HOSTS}={ALLOW_HOSTS_VALUE}")
    else:
        lines.append(f"export {VAR_ALLOW_HOSTS}={ALLOW_HOSTS_VALUE}")
    lines.append("")
    return "\n".join(lines)


def write_atomic(target: Path, content: str) -> None:
    """tempfile in target dir + fsync + os.replace, mode 0644."""
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path_str = tempfile.mkstemp(
        prefix=".env.sh.",
        dir=str(target.parent),
        text=False,
    )
    tmp_path = Path(tmp_path_str)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
        os.chmod(tmp_path, 0o644)
        os.replace(tmp_path, target)
    except OSError:
        try:
            tmp_path.unlink()
        except OSError:
            pass
        raise


def main(argv: list[str]) -> int:
    home = Path(os.environ.get("HOME") or os.path.expanduser("~"))
    default_target = home / ".config" / "clearance" / "env.sh"

    parser = argparse.ArgumentParser(
        description="Render the clearance env sidecar (~/.config/clearance/env.sh).",
    )
    parser.add_argument(
        "--target",
        default=str(default_target),
        help=f"Sidecar path (default: {default_target}).",
    )
    args = parser.parse_args(argv)

    rc_conflicts = scan_rc(home, (VAR_ALLOW_HOSTS, VAR_PERSONAL))
    content = render_sidecar(rc_conflicts)
    target = Path(args.target)

    try:
        write_atomic(target, content)
    except OSError as exc:
        print(json.dumps({
            "target": str(target),
            "wrote": False,
            "error": f"{exc.__class__.__name__}: {exc}",
        }))
        return 1

    print(json.dumps({
        "target": str(target),
        "wrote": True,
        "rcConflicts": list(rc_conflicts.values()),
    }))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
