#!/usr/bin/env python3
"""Render a groundcrew crew.config.ts from a JSON Answers object on stdin.

Usage:
    echo '<answers-json>' | python3 render_config.py --target /path/to/config.ts

Exits 0 and prints the absolute path of the written file on success.
Exits 2 on validation errors (stderr describes the problem).
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path
from typing import Any

VALID_WORKSPACE_KINDS = {"auto", "cmux", "tmux"}

GENERATED_HEADER = """\
// Generated by /groundcrew-setup:config. Re-run the wizard or edit by hand;
// either is safe. See: https://github.com/paulbaranowski/wild-horses
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="render_config.py",
        description="Render a groundcrew config.ts from JSON Answers on stdin.",
    )
    parser.add_argument(
        "--target",
        required=True,
        help="Path where config.ts will be written.",
    )
    return parser.parse_args()


def load_answers() -> dict[str, Any]:
    """Read and parse JSON Answers from stdin. Exit 2 on parse failure."""
    raw = sys.stdin.read()
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        sys.stderr.write(f"ERROR: invalid JSON on stdin: {exc}\n")
        sys.exit(2)
    if not isinstance(data, dict):
        sys.stderr.write("ERROR: JSON root must be an object\n")
        sys.exit(2)
    return data


def validate_answers(answers: dict[str, Any]) -> None:
    """Validate required and typed fields. Exit 2 on any violation."""
    errors: list[str] = []

    # Required: workspaceProjectDir
    if "workspaceProjectDir" not in answers:
        errors.append("missing required field: workspaceProjectDir")
    elif not isinstance(answers["workspaceProjectDir"], str) or not answers["workspaceProjectDir"]:
        errors.append("workspaceProjectDir must be a non-empty string")

    # Required: knownRepositories
    if "knownRepositories" not in answers:
        errors.append("missing required field: knownRepositories")
    else:
        repos = answers["knownRepositories"]
        if not isinstance(repos, list):
            errors.append("knownRepositories must be a list")
        else:
            for i, repo in enumerate(repos):
                if not isinstance(repo, str) or not repo:
                    errors.append(f"knownRepositories[{i}] must be a non-empty string")

    # Optional: workspaceKind
    wk = answers.get("workspaceKind", "auto")
    if not isinstance(wk, str) or wk not in VALID_WORKSPACE_KINDS:
        errors.append(
            f"workspaceKind must be one of {sorted(VALID_WORKSPACE_KINDS)!r}; got {wk!r}"
        )

    # Optional: promptFeatures
    pf = answers.get("promptFeatures", [])
    if not isinstance(pf, list):
        errors.append("promptFeatures must be a list")
    else:
        for i, feat in enumerate(pf):
            if not isinstance(feat, str):
                errors.append(f"promptFeatures[{i}] must be a string")

    # Optional: sessionLimitPercentage
    slp = answers.get("sessionLimitPercentage")
    if slp is not None:
        if isinstance(slp, bool) or not isinstance(slp, int) or not (1 <= slp <= 100):
            errors.append("sessionLimitPercentage must be an integer in 1..100")

    # Optional: claudeBypassPermissions type check
    cbp = answers.get("claudeBypassPermissions")
    if cbp is not None and not isinstance(cbp, bool):
        errors.append("claudeBypassPermissions must be a boolean")

    # Optional: modelClaude type check
    mc = answers.get("modelClaude")
    if mc is not None and not isinstance(mc, dict):
        errors.append("modelClaude must be an object")

    # Optional: modelCodex type check
    mcx = answers.get("modelCodex")
    if mcx is not None and not isinstance(mcx, dict):
        errors.append("modelCodex must be an object")

    # Optional: loggingFile type check
    lf = answers.get("loggingFile")
    if lf is not None and (not isinstance(lf, str) or not lf):
        errors.append("loggingFile must be a non-empty string if set")

    if errors:
        for err in errors:
            sys.stderr.write(f"ERROR: {err}\n")
        sys.exit(2)


def render_known_repositories(repos: list[str], indent: str) -> str:
    """Render knownRepositories as single-line (<=3) or multi-line (>3)."""
    inner_indent = indent + "  "
    # 3 or fewer repos fit on one line comfortably; 4+ are folded onto separate lines for readability.
    if len(repos) <= 3:
        items = ", ".join(json.dumps(r) for r in repos)
        return f"[{items}]"
    else:
        lines = [inner_indent + json.dumps(r) + "," for r in repos]
        return "[\n" + "\n".join(lines) + "\n" + indent + "]"


def render_workspace_block(answers: dict[str, Any]) -> str:
    """Render the always-emitted workspace block."""
    project_dir = json.dumps(answers["workspaceProjectDir"])
    repos = answers["knownRepositories"]
    repos_rendered = render_known_repositories(repos, indent="    ")
    return (
        f"  workspace: {{\n"
        f"    projectDir: {project_dir},\n"
        f"    knownRepositories: {repos_rendered},\n"
        f"  }}"
    )


def render_models_block(answers: dict[str, Any]) -> str | None:
    """Render models.definitions if needed, or return None to omit."""
    bypass = answers.get("claudeBypassPermissions", False)
    model_claude: dict[str, Any] | None = answers.get("modelClaude")
    model_codex: dict[str, Any] | None = answers.get("modelCodex")

    # Determine claude cmd
    claude_cmd: str | None = None
    if model_claude and isinstance(model_claude.get("cmd"), str):
        claude_cmd = model_claude["cmd"]
    elif bypass:
        claude_cmd = "claude --permission-mode bypassPermissions"

    # Determine codex cmd
    codex_cmd: str | None = None
    if model_codex and isinstance(model_codex.get("cmd"), str):
        codex_cmd = model_codex["cmd"]

    if claude_cmd is None and codex_cmd is None:
        return None

    inner_lines: list[str] = []
    if claude_cmd is not None:
        inner_lines.append(f"      claude: {{ cmd: {json.dumps(claude_cmd)} }},")
    if codex_cmd is not None:
        inner_lines.append(f"      codex: {{ cmd: {json.dumps(codex_cmd)} }},")

    definitions = "\n".join(inner_lines)
    return (
        f"  models: {{\n"
        f"    definitions: {{\n"
        f"{definitions}\n"
        f"    }},\n"
        f"  }}"
    )


def render_orchestrator_block(answers: dict[str, Any]) -> str | None:
    """Render orchestrator block if sessionLimitPercentage is set."""
    slp = answers.get("sessionLimitPercentage")
    if slp is None:
        return None
    return f"  orchestrator: {{ sessionLimitPercentage: {slp} }}"


def render_prompts_block() -> str:
    """Render prompts block (only called when promptFeatures is non-empty)."""
    return (
        "  prompts: {\n"
        '    initial: readFileSync(new URL("./initial-prompt.md", import.meta.url), "utf8"),\n'
        "  }"
    )


def render_logging_block(answers: dict[str, Any]) -> str | None:
    """Render logging block if loggingFile is set."""
    lf = answers.get("loggingFile")
    if lf is None:
        return None
    return f"  logging: {{ file: {json.dumps(lf)} }}"


def render_config(answers: dict[str, Any]) -> str:
    """Assemble the full config.ts content from validated answers."""
    prompt_features: list[str] = answers.get("promptFeatures", [])
    needs_readfilesync = len(prompt_features) > 0

    workspace_kind: str = answers.get("workspaceKind", "auto")
    emit_workspace_kind = workspace_kind != "auto"

    # Build import block
    imports: list[str] = ['import type { Config } from "@clipboard-health/groundcrew";']
    if needs_readfilesync:
        imports.append('import { readFileSync } from "node:fs";')

    # Build body blocks
    body_blocks: list[str] = [render_workspace_block(answers)]

    if emit_workspace_kind:
        body_blocks.append(f"  workspaceKind: {json.dumps(workspace_kind)}")

    models_block = render_models_block(answers)
    if models_block is not None:
        body_blocks.append(models_block)

    orchestrator_block = render_orchestrator_block(answers)
    if orchestrator_block is not None:
        body_blocks.append(orchestrator_block)

    if needs_readfilesync:
        body_blocks.append(render_prompts_block())

    logging_block = render_logging_block(answers)
    if logging_block is not None:
        body_blocks.append(logging_block)

    # Join body blocks with trailing commas
    body = ",\n".join(body_blocks)

    lines: list[str] = []
    lines.append(GENERATED_HEADER)
    lines.append("\n".join(imports))
    lines.append("")
    lines.append("export default {")
    lines.append(body + ",")
    lines.append("} satisfies Config;")

    return "\n".join(lines) + "\n"


def write_atomic(target: Path, content: str) -> None:
    """Write content to target atomically: tmp file + fsync + os.replace."""
    target.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(dir=target.parent, suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
    except Exception:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise
    os.replace(tmp_path, target)


def main() -> None:
    args = parse_args()
    answers = load_answers()
    validate_answers(answers)

    content = render_config(answers)
    target = Path(args.target).expanduser().resolve()
    write_atomic(target, content)

    sys.stdout.write(str(target) + "\n")


if __name__ == "__main__":
    main()
