#!/usr/bin/env python3
"""Tests for pr_babysit_cli.py.

Stdlib-only - no pytest needed. Run from anywhere:

    python3 plugins/pr/scripts/test_pr_babysit_cli.py

Or via unittest discovery:

    python3 -m unittest discover -s plugins/pr/scripts -p 'test_pr_babysit_cli.py'

The golden fixtures under fixtures/ were generated by running the ORIGINAL bash
scripts' real jq/shasum logic against recorded gh responses (see the design doc).
`transform_review` and `partition_failing_checks` must reproduce them exactly -
that is the regression guarantee that the jq -> Python translation is faithful.
"""
import json
import subprocess
import sys
import unittest
from pathlib import Path

HERE = Path(__file__).parent
FIXTURES = HERE / "fixtures"
CLI = HERE / "pr_babysit_cli.py"

sys.path.insert(0, str(HERE))
import pr_babysit_cli as cli  # noqa: E402


def load(name):
    return json.loads((FIXTURES / name).read_text())


def bash_fingerprint(body):
    """Compute the fingerprint the way the old bash did, to cross-check ours."""
    pipeline = (
        "printf '%s' \"$1\" | tr -s '[:space:]' ' ' | sed -E 's/^ //; s/ $//' "
        "| shasum -a 256 | cut -c1-16 | tr -d '\\n'"
    )
    out = subprocess.run(["bash", "-c", pipeline, "_", body],
                         stdout=subprocess.PIPE, text=True)
    return out.stdout


class TestFingerprint(unittest.TestCase):
    def test_normalize_collapses_and_trims(self):
        self.assertEqual(cli.normalize_body("  a\n\n\t b  "), "a b")
        self.assertEqual(cli.normalize_body("no-change"), "no-change")
        self.assertEqual(cli.normalize_body(""), "")

    def test_matches_bash_shasum(self):
        for body in ["hello world",
                     "  Leading and trailing  ",
                     "multi\nline\n\nbody\twith\ttabs",
                     "unicode: café and emoji \U0001F916 stay"]:
            self.assertEqual(cli.fingerprint_body(body), bash_fingerprint(body),
                             msg=f"fingerprint drift for {body!r}")

    def test_fingerprint_is_16_hex(self):
        fp = cli.fingerprint_body("anything")
        self.assertEqual(len(fp), 16)
        int(fp, 16)  # raises if not hex


class TestBotAndSentinel(unittest.TestCase):
    def test_is_bot_typename(self):
        self.assertTrue(cli.is_bot("whoever", "Bot"))

    def test_is_bot_allowlist(self):
        self.assertTrue(cli.is_bot("coderabbitai", "User"))
        self.assertTrue(cli.is_bot("dependabot[bot]", "User"))

    def test_is_bot_human(self):
        self.assertFalse(cli.is_bot("alice", "User"))

    def test_is_sentinel_current_and_legacy(self):
        self.assertTrue(cli.is_sentinel_body("x " + cli.SENTINEL_PREFIX + "y"))
        self.assertTrue(cli.is_sentinel_body("cb-babysit:addressed v1 z"))
        self.assertTrue(cli.is_sentinel_body("babysit-pr:addressed v1 z"))
        self.assertFalse(cli.is_sentinel_body("just a normal comment"))

    def test_ensure_sentinel_appends_once(self):
        got = cli.ensure_sentinel("body text")
        self.assertTrue(got.endswith(cli.SENTINEL))
        self.assertEqual(got, "body text\n\n" + cli.SENTINEL)

    def test_ensure_sentinel_idempotent(self):
        already = "body\n\n" + cli.SENTINEL
        self.assertEqual(cli.ensure_sentinel(already), already)

    def test_ensure_sentinel_preserves_legacy(self):
        body = "handled cb-babysit:addressed v1 already"
        self.assertEqual(cli.ensure_sentinel(body), body)


class TestReviewGoldenParity(unittest.TestCase):
    def _assert_golden(self, response_file, golden_file, pr_number, fixed):
        response = load(response_file)
        golden = load(golden_file)
        got = cli.transform_review(response, pr_number, "paulbaranowski",
                                   "wild-horses", fixed)
        # Compare via canonical JSON so key order is irrelevant.
        self.assertEqual(json.loads(json.dumps(got, sort_keys=True)),
                         json.loads(json.dumps(golden, sort_keys=True)))

    def test_synthetic_all_branches(self):
        # Alert 42 fixed, 99 not - matches how the golden was generated.
        self._assert_golden("synthetic_response.json", "golden_synthetic.json",
                            1, {"42"})

    def test_real_pr163(self):
        self._assert_golden("real_pr163_response.json", "golden_pr163.json",
                            163, set())

    def test_real_pr169_near_empty(self):
        self._assert_golden("real_pr169_response.json", "golden_pr169.json",
                            169, set())


class TestReviewBranches(unittest.TestCase):
    """Targeted assertions on top of the golden deep-equal, for readability."""

    def setUp(self):
        self.doc = cli.transform_review(load("synthetic_response.json"), 1,
                                        "paulbaranowski", "wild-horses", {"42"})

    def _thread(self, tid):
        return next(t for t in self.doc["threads"] if t["threadId"] == tid)

    def test_activity_states(self):
        self.assertEqual(self._thread("TA")["activityState"], "active")   # no sentinel
        self.assertEqual(self._thread("TB")["activityState"], "active")   # human after sentinel
        self.assertEqual(self._thread("TC")["activityState"], "uncertain")  # bot after sentinel
        self.assertEqual(self._thread("TD")["activityState"], "addressed")  # sentinel newest

    def test_resolved_thread_excluded(self):
        self.assertNotIn("TE", [t["threadId"] for t in self.doc["threads"]])

    def test_uncertain_carries_post_sentinel_bot(self):
        tc = self._thread("TC")
        self.assertEqual([c["author"] for c in tc["postSentinelBotComments"]],
                         ["coderabbitai"])
        self.assertEqual(tc["postSentinelHumanComments"], [])

    def test_fixed_alert_filtered_unfixed_kept(self):
        bodies = [c["body"] for c in self.doc["unresolvedComments"]
                  if "code-scanning" in (c["body"] or "")]
        self.assertTrue(any("/code-scanning/99" in b for b in bodies))
        self.assertFalse(any("/code-scanning/42" in b for b in bodies))

    def test_review_bodies_bot_only_nonempty(self):
        self.assertEqual(self.doc["totalReviewBodyComments"], 1)
        self.assertEqual(self.doc["reviewBodyComments"][0]["author"], "coderabbitai")

    def test_active_issue_comment_dedupe(self):
        # frank is active; grace is deduped by fingerprint; codecov is a bot;
        # the prior-sentinel comment is excluded.
        self.assertEqual([c["author"] for c in self.doc["activeIssueComments"]],
                         ["frank"])
        self.assertEqual(len(self.doc["priorBabysitSentinels"]), 1)

    def test_truncation_surfaced(self):
        self.assertEqual(self.doc["truncated"], ["reviewThreads"])

    def test_prnumber_is_int(self):
        self.assertEqual(self.doc["prNumber"], 1)
        self.assertIsInstance(self.doc["prNumber"], int)


class TestFailingChecks(unittest.TestCase):
    def test_none(self):
        rollup = load("rollup_none.json")
        run_ids, external, any_failing = cli.partition_failing_checks(rollup)
        self.assertFalse(any_failing)
        self.assertEqual(run_ids, [])
        self.assertEqual(external, [])

    def test_external_only_matches_golden(self):
        rollup = load("rollup_external.json")
        run_ids, external, any_failing = cli.partition_failing_checks(rollup)
        self.assertTrue(any_failing)
        self.assertEqual(run_ids, [])
        golden = (FIXTURES / "golden_logs_external.txt").read_text()
        for line in external:
            self.assertIn(line, golden)
        # Nx Cloud's /runs/ path must NOT be mistaken for a GitHub Actions run.
        self.assertTrue(any("nx-cloud" in ln for ln in external))
        self.assertTrue(any("CircleCI" in ln for ln in external))

    def test_actions_run_extracted(self):
        rollup = [{
            "name": "ci", "conclusion": "FAILURE", "bucket": "fail",
            "detailsUrl": "https://github.com/o/r/actions/runs/12345/job/9",
        }]
        run_ids, external, any_failing = cli.partition_failing_checks(rollup)
        self.assertEqual(run_ids, ["12345"])
        self.assertEqual(external, [])

    def test_null_bucket_error_state_is_failure(self):
        rollup = [{"name": "status", "bucket": None, "state": "ERROR",
                   "detailsUrl": "https://ci.example.com/x"}]
        run_ids, external, any_failing = cli.partition_failing_checks(rollup)
        self.assertTrue(any_failing)
        self.assertEqual(run_ids, [])
        self.assertEqual(len(external), 1)

    def test_run_ids_deduped(self):
        rollup = [
            {"name": "a", "bucket": "fail", "detailsUrl": "https://github.com/o/r/actions/runs/7"},
            {"name": "b", "bucket": "fail", "detailsUrl": "https://github.com/o/r/actions/runs/7/job/2"},
        ]
        run_ids, _, _ = cli.partition_failing_checks(rollup)
        self.assertEqual(run_ids, ["7"])


class TestCliSurface(unittest.TestCase):
    """Subprocess-level: exit codes and error channels as an agent sees them."""

    def run_cli(self, args, stdin=None):
        return subprocess.run([sys.executable, str(CLI), *args],
                              input=stdin, stdout=subprocess.PIPE,
                              stderr=subprocess.PIPE, text=True)

    def test_no_subcommand_exits_2(self):
        self.assertEqual(self.run_cli([]).returncode, 2)

    def test_review_bad_pr_error_on_stdout(self):
        proc = self.run_cli(["review", "notanumber"])
        self.assertEqual(proc.returncode, 1)
        payload = json.loads(proc.stdout)  # error is JSON on STDOUT for review
        self.assertIn("Invalid PR number", payload["error"])
        self.assertEqual(proc.stderr, "")

    def test_failed_logs_bad_pr_exits_2(self):
        proc = self.run_cli(["failed-logs", "xyz"])
        self.assertEqual(proc.returncode, 2)
        self.assertIn("error", json.loads(proc.stderr))

    def test_commit_push_missing_files_exits_2(self):
        proc = self.run_cli(["commit-push", "msg"])
        self.assertEqual(proc.returncode, 2)
        self.assertIn("error", json.loads(proc.stderr))

    def test_comment_bad_pr_exits_2(self):
        proc = self.run_cli(["comment", "nope"], stdin="a body")
        self.assertEqual(proc.returncode, 2)
        self.assertIn("Invalid PR number", json.loads(proc.stderr)["error"])

    def test_reply_empty_body_exits_2(self):
        proc = self.run_cli(["reply", "THREAD"], stdin="")
        self.assertEqual(proc.returncode, 2)
        self.assertIn("body is required", json.loads(proc.stderr)["error"])


if __name__ == "__main__":
    unittest.main()
